# Generated by Django 5.2.8 on 2025-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(default='a', max_length=200, verbose_name='Nombre de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='password_hash',
            field=models.CharField(default='1', max_length=128, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
