# Generated by Django 5.2.8 on 2025-12-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_remove_proveedor_usuario_proveedor_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, choices=[('', 'Selecciona un país'), ('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Perú'), ('BO', 'Bolivia'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('MX', 'México'), ('UY', 'Uruguay'), ('PY', 'Paraguay')], max_length=2, null=True, verbose_name='País'),
        ),
        migrations.RemoveField(
            model_name='region',
            name='pais',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='proveedor.categoriaproveedor', verbose_name='Rubros que oferta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
