# Generated by Django 5.2.5 on 2025-12-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_post_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Aviso')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('CAPACITACION', 'Capacitación'), ('EVENTO', 'Evento'), ('SORTEO', 'Sorteo/Concurso'), ('GENERAL', 'General/Aviso')], default='GENERAL', max_length=50, verbose_name='Tipo de Aviso')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso de Administración',
                'verbose_name_plural': 'Avisos de Administración',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AvisoLeido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='usuarios.aviso')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_leidos', to='usuarios.comerciante')),
            ],
            options={
                'verbose_name': 'Aviso Leído',
                'verbose_name_plural': 'Avisos Leídos',
                'unique_together': {('aviso', 'comerciante')},
            },
        ),
    ]
